apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "kosmos.fullname" . }}-api
  labels:
    {{- include "kosmos.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable | default 1 }}
  selector:
    matchLabels:
      {{- include "kosmos.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
