apiVersion: v1
kind: Service
metadata:
  name: {{ include "kosmos.fullname" . }}-api
  labels:
    {{- include "kosmos.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port | default 8000 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kosmos.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
