apiVersion: apps/v1
kind: Deployment
metadata:
  name: kosmos-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kosmos-frontend
  template:
    metadata:
      labels:
        app: kosmos-frontend
    spec:
      containers:
        - name: kosmos-frontend
          image: kosmos-frontend:v1.0.0
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API_URL
              value: "http://kosmos-backend:8000"
            - name: API_INTERNAL_URL
              value: "http://kosmos-backend:8000"
---
apiVersion: v1
kind: Service
metadata:
  name: kosmos-frontend
spec:
  selector:
    app: kosmos-frontend
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
